name: tes_tsa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  android_intent_plus:
  shared_preferences: ^2.0.15
  crypto: ^3.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/


